implemented method get, functions getAll and getById, added file with…
html-hooliganz/product_catalog_backend pull request #2
Opened 2023-07-29 16:46 UTC by vladyslav-lapshyn

Added file with data, implement controllers, services, routes

2023-07-29 19:17 UTC, ruslanpashkov requested changes

2023-07-29 19:17 UTC, ruslanpashkov commented on src/controllers/phones.controller.ts
> +export const getAllPhonesController: Controller = async (_, res) => {
```suggestion
export const getAllPhonesController: Controller = async (req, res) => {
```

2023-07-29 19:17 UTC, ruslanpashkov commented on src/controllers/phones.controller.ts
> +  res.send(phones);
```suggestion
  res.status(200).json(phones);
```

2023-07-29 19:17 UTC, ruslanpashkov commented on src/controllers/phones.controller.ts
> +  res.send(foundPhone);
```suggestion
  res.status(200).json(foundPhone);
```

2023-07-29 19:17 UTC, ruslanpashkov commented on src/routes/phones.router.ts
> +phonesRouter.get('/:phoneId', getPhoneByIdController);
```suggestion
phonesRouter.get('/', getAllPhonesController);
phonesRouter.get('/:phoneId', getPhoneByIdController);
```

2023-07-29 19:17 UTC, ruslanpashkov commented on src/server.ts
> +import { phonesRouter } from './routes/phones.router.js';
You don't need to use separations in imports

```suggestion
import express from 'express';
import cors from 'cors';
import { phonesRouter } from './routes/phones.router.js';
```

2023-07-29 19:17 UTC, ruslanpashkov commented on src/server.ts
> +  app.use('/', (_, res) => {
```suggestion
  app.use(cors());
  app.use('/phones', express.json(), phonesRouter);
  app.use('/', (req, res) => {
```

2023-07-29 19:17 UTC, ruslanpashkov commented on src/types.ts
> +}
There is no problem, but make sure that every field is required (we can have unnecessary fields also)

2023-07-29 19:17 UTC, ruslanpashkov commented on src/controllers/phones.controller.ts
> +  const phoneService = new PhonesService();
Let's do it inside `src/services/phones.service.ts` and export this variable instead of class, also you can read about **Singleton pattern** to make sure that we will have only one instance of this class

2023-07-29 19:26 UTC, vladyslav-lapshyn commented on src/server.ts
> +import { phonesRouter } from './routes/phones.router.js';
@ruslanpashkov I thought it's better if I separated logic blocks, but okay, I understand, thanks

2023-07-29 19:29 UTC, vladyslav-lapshyn commented on src/types.ts
> +}
@ruslanpashkov you're right, but I'm not sure if we need it now, because when I will connect to DB I delete that interface, because I will use modules

2023-07-29 20:19 UTC, vladyslav-lapshyn commented on src/controllers/phones.controller.ts
> +  const phoneService = new PhonesService();
genius

2023-07-30 10:19 UTC, ruslanpashkov approved these changes

2023-07-30 10:20 UTC, merged